staging:
  password: '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'
  theme_id: '116657422535'
  store: 'gem-and-beauty-forever.myshopify.com'
preproduction:
  password: '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'
  theme_id: '116657488071'
  store: 'gem-and-beauty-forever.myshopify.com'
master:
  password: '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'
  theme_id: '116657389767'
  store: 'gem-and-beauty-forever.myshopify.com'


branch:
  password: ${SHOPIFY_BRANCH_PASSWORD}
  theme_id: ${SHOPIFY_BRANCH_THEME_ID}
  store: ${SHOPIFY_BRANCH_STORE_URL}